TakedaAnalitic/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.views.generic import RedirectView

from bi_auth.views import loginView, logoutView, bi_login
from widgetpages.views import HomeView

urlpatterns = [
    path('', bi_login(HomeView.as_view()), name='home'),
    path('login/', loginView, name='login'),
    path('logout/', logoutView, name='logout'),
    path('page/', include(('widgetpages.urls', 'widgetpages'), namespace='widgetpages')),
    path('data/', include(('dataloader.urls', 'dataloader'), namespace='data')),
    path('fadmin/', include(('farmadmin.urls', 'farmadmin'), namespace='farmadmin')),
    # path('proto/', include(('protocols.urls', 'protocols'), namespace='protocols')),
    path('admin/', admin.site.urls, name='admin'),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico'), name='favicon'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

dataloader/urls.py
from django.contrib import admin
from django.urls import path

from bi_auth.views import bi_login
from dataloader import views

urlpatterns = [
    path('filters/', bi_login(views.FiltersAjaxTable.as_view()), name='filters'),
    path('filter/save/', bi_login(views.FiltersSaveView.as_view()), name='filter_save'),
    path('filter/delete/', bi_login(views.FiltersDeleteView.as_view()), name='filter_delete'),
    path('filter/load/', bi_login(views.FiltersLoadView.as_view()), name='filter_load'),
    path('meta/', bi_login(views.CacheMetaView.as_view()), name='meta'),
    path('fk/<str:fk_name>/', bi_login(views.FkFieldView.as_view()), name='fk'),
    path('fk/<str:fk_name>/<str:search_text>/', bi_login(views.FkFieldView.as_view()), name='fk'),
    path('dl/', bi_login(views.DownloadView.as_view()), name='dl'),
    path('dlxls/', bi_login(views.DownloadXlsView.as_view()), name='dlxls'),
]

farmadmin/urls.py
from django.urls import path

from bi_auth.views import bi_login
from farmadmin import views


urlpatterns = [
    path('orgselect/', bi_login(views.OrgView.as_view()), name='orgselect'),
    path('setuporg/', bi_login(views.SetupOrgView.as_view()), name='setuporg'),

    path('employees/', bi_login(views.EmployeesAdminView.as_view()), name='employees'),
    #path('employee/<int:pk>/', bi_login(views.EmployeeUpdateAdminView.as_view()), name='employee'),
    path('employee/', bi_login(views.EmployeeCreateBaseAdminView.as_view()), name='employee_base'),
    path('employee/<int:pk>/', bi_login(views.EmployeeUpdateBaseAdminView.as_view()), name='employee_base'),
    path('employee/lpu/<int:pk>/', bi_login(views.EmployeeUpdateLpuAdminView.as_view()), name='employee_lpu'),
    path('employee/user/<int:pk>/', bi_login(views.EmployeeUpdateUserAdminView.as_view()), name='employee_user'),
    path('employee/reg/<int:pk>/', bi_login(views.EmployeeUpdateRegAdminView.as_view()), name='employee_reg'),
    path('employee/regquery/', bi_login(views.EmployeeQueryRegAdminView.as_view()), name='employee_regquery'),
    path('employee/rm/<int:pk>/', bi_login(views.EmployeeDeleteAdminView.as_view()), name='employee_rm'),

    path('markets/', bi_login(views.MarketsAdminView.as_view()), name='markets'),
    path('market/<int:pk>/', bi_login(views.MarketUpdateAdminView.as_view()), name='market'),
    path('market/rm/<int:pk>/', bi_login(views.MarketDeleteAdminView.as_view()), name='market_rm'),
    path('market/', bi_login(views.MarketCreateAdminView.as_view()), name='market'),

    path('orgs/', bi_login(views.OrgsAdminView.as_view()), name='orgs'),
    path('org/<int:pk>/', bi_login(views.OrgUpdateAdminView.as_view()), name='org'),
    path('org/rm/<int:pk>/', bi_login(views.OrgDeleteAdminView.as_view()), name='org_rm'),
    path('org/', bi_login(views.OrgCreateAdminView.as_view()), name='org'),

    path('jlpuall/datatable/', bi_login(views.AjaxLpuAllDatatableView.as_view()), name='jlpuall'),
    path('success/', views.SuccessView.as_view(), name='success'),
]

widgetpages/urls.py
from django.contrib import admin
from django.urls import path

from bi_auth.views import bi_login
from widgetpages import views
from widgetpages import table_filters

urlpatterns = [
    path('jdata/datatable/', bi_login(table_filters.FilterListJson.as_view()), name='jdata'),
    path('jdata/passport/', bi_login(table_filters.PassportFilterListJson.as_view()), name='jdata_passport'),
    path('salesshedule/', bi_login(views.SalessheduleView.as_view()), name='salesshedule'),
    path('competitions/lpu/', bi_login(views.CompetitionsLpuView.as_view()), name='competitions_lpu'),
    path('competitions/market/', bi_login(views.CompetitionsMarketView.as_view()), name='competitions_market'),
    path('jcompetitions_lpu/datatable/', bi_login(views.Lpu_CompetitionsAjaxTable.as_view()), name='jcompetitions_lpu'),
    path('jcompetitions_market/datatable/', bi_login(views.Market_CompetitionsAjaxTable.as_view()), name='jcompetitions_market'),
    path('avg/market/', bi_login(views.AvgMarketView.as_view()), name='avg_price'),
    path('javg_market/datatable/', bi_login(views.AvgAjaxTable.as_view()),name='javg_price'),
    path('pkgs/market/', bi_login(views.PackagesView.as_view()), name='packages'),
    path('jpkgs/datatable/', bi_login(views.PackagesAjaxTable.as_view()), name='jpackages'),
    path('parts/', bi_login(views.PartsView.as_view()), name='parts'),
    path('jparts/datatable1/', bi_login(views.MPartsAjaxTable.as_view()), name='jmparts'),
    path('jparts/datatable2/', bi_login(views.LPartsAjaxTable.as_view()), name='jlparts'),
    path('sales_analysis/', bi_login(views.SalesAnlysisView.as_view()), name='sales_analysis'),
    path('jsales_analysis/datatable/', bi_login(views.SalesAnlysisAjaxTable.as_view()), name='jsales_analysis'),
    path('budgets/', bi_login(views.BudgetsView.as_view()), name='budgets'),
    path('budgets/datatable/', bi_login(views.BudgetsAjaxTable.as_view()), name='budgets_table'),
    path('passport/', bi_login(views.PassportView.as_view()), name='passport'),
    path('passport/datatable/winners/', bi_login(views.PassportWinnersAjaxTable.as_view()), name='passport_winners_table'),
    path('download/<str:file_name>/', bi_login(views.DownloadXlsFile), name='download_xls'),
    path('download/<str:file_name>/<int:remove>/', bi_login(views.DownloadXlsFile), name='download_xls'),
]

db/models.py
from django.db import models
from django.contrib.auth.models import User

DB_VERSION = '0.10'

DB_READY = 0
DB_UPDATE = 1
DB_RECREATE = 2
DB_OFFLINE = 3
DB_ERROR = 4

ST_NONE = 0
ST_LOAD = 1
ST_SUCCESS = 2
ST_FAILED = 3

SYNC_STATUS_CHOICES = (
    (DB_READY, 'БД в работе'),
    (DB_UPDATE, 'БД обновляется'),
    (DB_RECREATE, 'БД формируется'),
    (DB_OFFLINE, 'БД на обслуживании'),
    (DB_ERROR, 'Сбой БД'),
)

class Org(models.Model):
    name = models.CharField(max_length=32, null=True, blank=True, verbose_name='Организация')
    sync_time = models.CharField(verbose_name='Время синхронизации', max_length=5, null=True, blank=True, default='')
    sync_flag = models.BooleanField(default=False, verbose_name='Запустить формирование БД', null=False, blank=True)
    sync_status = models.IntegerField(default=0, verbose_name='Состояние синхронизации', null=False, blank=True, choices = SYNC_STATUS_CHOICES)
    users = models.ManyToManyField(User, verbose_name='Логин входа', blank=True)
    db_version = models.CharField(verbose_name='Версия БД', max_length=5, null=True, blank=True, default='0.00')
    last_sync_dt = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name = 'Организация'
        verbose_name_plural = 'Организации'

    def __str__(self):
         return  self.name

class Org_log(models.Model):
    org = models.ForeignKey(Org, on_delete=models.CASCADE)
    time = models.DateTimeField(null=False, blank=False, auto_now_add=True)
    description = models.CharField(max_length=128, null=False, blank=False, verbose_name='Сообщение')

    class Meta:
        verbose_name = 'Событие БД'
        verbose_name_plural = 'События БД'

    def __str__(self):
         return  self.description

class Lpu(models.Model):
    cust_id = models.IntegerField(db_column='Cust_ID', primary_key=True, db_index=True, null=False, blank=False)
    inn = models.CharField(db_column='Org_CustINN', max_length=16, db_index=True, null=False, blank=False, verbose_name='ИНН')
    name = models.CharField(db_column='Org_CustNm', max_length=512, db_index=True, null=False, blank=False, verbose_name='Грузополучатель')
    shortname = models.CharField(db_column='shortname', max_length=512, null=True, blank=True, verbose_name='Грузополучатель полное имя')
    addr1 = models.CharField(db_column='addr1', max_length=512, null=True, blank=True, verbose_name='Адрес1')
    addr2 = models.CharField(db_column='addr2', max_length=512, null=True, blank=True, verbose_name='Адрес2')
    regcode = models.ForeignKey('Region', db_column='regcode', null=True, verbose_name='Код региона', on_delete=models.SET_NULL)
    employee = models.ManyToManyField('Employee', related_name='employees', verbose_name='Сотрудник')

    class Meta:
        verbose_name = 'Грузополучатель'
        verbose_name_plural = 'Грузополучатели'
        managed = False
        db_table = 'db_lpu'

    def __str__(self):
         return  self.inn if self.inn else ''+' '+self.name if self.name else ''

class Region(models.Model):
    reg_id = models.IntegerField(db_column='Reg_ID', primary_key=True, db_index=True, null=False, blank=False)
    regnm = models.CharField(db_column='RegNm', max_length=50, db_index=True, null=False, blank=False, verbose_name='Название региона')
    employee = models.ManyToManyField('Employee', related_name='region_employees', verbose_name='Сотрудник')

    class Meta:
        verbose_name = 'Регион'
        verbose_name_plural = 'Регионы'
        managed = False
        db_table = 'db_region'

    def __str__(self):
         return  self.regnm

class Employee(models.Model):
    org = models.ForeignKey(Org, on_delete=models.CASCADE, verbose_name='Организация')
    parent = models.ForeignKey('self',on_delete=models.SET_NULL, null=True, blank=True, db_index=True, verbose_name='Руководитель')
    name = models.CharField(max_length=64, null=True, blank=True,verbose_name='Краткое имя')
    users = models.ManyToManyField(User, related_name='employee_user', verbose_name='Логин входа', blank=True)
    istarget = models.BooleanField(default=True, db_index=True, verbose_name='Таргет')
    lpu = models.ManyToManyField('Lpu', through=Lpu.employee.through, related_name='lpus', blank=True, verbose_name='Грузополучатели') #Lpu.employee.through
    region = models.ManyToManyField('Region', through=Region.employee.through, related_name='employee_regions', blank=True, verbose_name='Регионы')  # Region.employee.through

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'

    def __str__(self):
         return self.name

class InNR(models.Model):
    id = models.IntegerField(db_column='id', primary_key=True, db_index=True, null=False, blank=False)
    name = models.CharField(db_column='name', max_length=300, null=False, blank=False)

    class Meta:
        managed = False
        db_table = 'db_innr'

    def __str__(self):
         return  self.name

class TradeNR(models.Model):
    id = models.IntegerField(db_column='id', primary_key=True, db_index=True, null=False, blank=False)
    name = models.CharField(db_column='name', max_length=254, null=False, blank=False)

    class Meta:
        managed = False
        db_table = 'db_tradenr'

    def __str__(self):
         return  self.name

class FO(models.Model):
    id = models.IntegerField(db_column='id', primary_key=True, db_index=True, null=False, blank=False)
    name = models.CharField(db_column='name', max_length=150, null=False, blank=False)

    class Meta:
        managed = False
        db_table = 'db_fo'

    def __str__(self):
         return  self.name

class Budget(models.Model):
    id = models.CharField(db_column='id', max_length=1, primary_key=True, db_index=True, null=False, blank=False)
    version = models.IntegerField(db_column='version', db_index=True, null=False, blank=False)
    name = models.CharField(db_column='name', max_length=200, null=False, blank=False)

    class Meta:
        managed = False
        db_table = 'db_budgets'

    def __str__(self):
         return  self.name

class Unit(models.Model):
    id = models.IntegerField(db_column='id', primary_key=True, db_index=True, null=False, blank=False)
    name = models.CharField(db_column='name', max_length=40, null=False, blank=False)
    shortname = models.CharField(db_column='shortname', max_length=40, null=False, blank=False)

    class Meta:
        managed = False
        db_table = 'db_unit'

    def __str__(self):
         return  self.name

class FormT(models.Model):
    id = models.IntegerField(db_column='id', primary_key=True, db_index=True, null=False, blank=False)
    name = models.CharField(db_column='name', max_length=50, null=False, blank=False)

    class Meta:
        managed = False
        db_table = 'db_formt'

    def __str__(self):
         return  self.name

class BProg(models.Model):
    id = models.IntegerField(db_column='id', primary_key=True, db_index=True, null=False, blank=False)
    name = models.CharField(db_column='name', max_length=200, null=False, blank=False)

    class Meta:
        managed = False
        db_table = 'db_bprog'

    def __str__(self):
         return  self.name

class Market(models.Model):
    org = models.ForeignKey(Org, on_delete=models.CASCADE, verbose_name='Организация')
    name = models.CharField(max_length=32, null=True, blank=True, verbose_name='Рынок')
    innrs = models.ManyToManyField(InNR, blank=True, through='Market_Innrs', verbose_name='МНН')
    tmnrs = models.ManyToManyField(TradeNR, blank=True, through='Market_Tmnrs', verbose_name='Торговые наименования')

    class Meta:
        verbose_name = 'Рынок'
        verbose_name_plural = 'Рынки'

    def __str__(self):
         return  self.name

class Market_Innrs(models.Model):
    market = models.ForeignKey(Market, on_delete=models.CASCADE)
    innr = models.ForeignKey(InNR, on_delete=models.CASCADE)
    own = models.IntegerField(default=0, null=False, blank=False)

class Market_Tmnrs(models.Model):
    market = models.ForeignKey(Market, on_delete=models.CASCADE)
    tradenr = models.ForeignKey(TradeNR, on_delete=models.CASCADE)
    own = models.IntegerField(default=0, null=False, blank=False)

class StatusT(models.Model):
    id = models.IntegerField(db_column='id', primary_key=True, db_index=True, null=False, blank=False)
    name = models.CharField(db_column='name', max_length=40, null=False, blank=False)

    class Meta:
        managed = False
        db_table = 'db_statusT'

class WinnerOrg(models.Model):
    id = models.IntegerField(db_column='id', primary_key=True, db_index=True, null=False, blank=False)
    name = models.CharField(db_column='name', max_length=512, null=False, blank=False)
    inn = models.CharField(db_column='inn', max_length=16, null=True, blank=True)

    class Meta:
        managed = False
        db_table = 'db_WinnerOrg'

class Filters(models.Model):
    user =  models.ForeignKey(User, verbose_name='Логин входа', null=True, blank=True, db_index=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=256, null=False, blank=False, db_index=True)
    fields_json = models.TextField(null=False, blank=False)
    filters_json = models.TextField(null=False, blank=False)
    created = models.DateTimeField(null=False, blank=False, auto_now_add=True)
    updated = models.DateTimeField(null=True, blank=True, auto_now=True)
    report_start = models.DateTimeField(null=True)
    report_finish = models.DateTimeField(null=True)
    status = models.IntegerField(null=False, default=ST_NONE)
    xls_url = models.CharField(max_length=128, null=True, blank=True)
    sendmail_create = models.IntegerField(null=False, default=0)
    sendmail_shedule = models.IntegerField(null=False, default=0)

    class Meta:
        verbose_name = 'Фильтр'
        verbose_name_plural = 'Фильтры'

    def __str__(self):
         return self.name

templates/dt_language.html
var lang_russian = {
                      "processing": "<i class='fa fa-cog fa-spin fa-3x fa-fw'></i>&nbsp;&nbsp;Подождите...",
                      //"search": "Поиск:",
                      "search": "<i class='fa fa-search'></i>",
                      "lengthMenu": "&nbsp;&nbsp;_MENU_&nbsp;&nbsp;",
                      "info": "Записи с _START_ до _END_ из _TOTAL_ ",
                      "infoEmpty": "Записи с 0 до 0 из 0 записей",
                      "infoFiltered": "",
                      //"infoFiltered": "(_MAX_ всего)",
                      "infoPostFix": "",
                      "loadingRecords": "Загрузка записей...",
                      "zeroRecords": "Записи отсутствуют.",
                      "emptyTable": "В таблице отсутствуют данные",
                      "paginate": {
                        "first": "Первая",
                        "previous": "Пред.",
                        "next": "След.",
                        "last": "Посл."
                      },
                      "aria": {
                        "sortAscending": ": активировать для сортировки столбца по возрастанию",
                        "sortDescending": ": активировать для сортировки столбца по убыванию"
                      },
                      "buttons": {
                        "selectAll": "Выбрать все",
                        "selectNone": "Снять выбор"
                      }
                    };

templates/dt_utils.html
function download_datatable_excel(url, view_id, org_id, dt) {
        var search_str = dt.search()
        var order = dt.order();

        data = { 'csrfmiddlewaretoken' : '{{ csrf_token }}',
                  'filters_ajax_request' : JSON.stringify(make_request()),
                  'view_id' : view_id,
                  'view_name' : '{{ view.name }}',
                  'org_id' : org_id,
                  'excel' : '1',
                  'search[value]': search_str,
                  'order[0][column]': order[0][0],
                  'order[0][dir]': order[0][1]
        };

        // Добавляем информацию о столбцах и порядке их следования, чтоюбы сработала сортировка
        var c = dt.settings().init().columnDefs;
        dt.columns().eq(0).each( function ( value, index ) {
            data['columns['+index.toString()+'][name]'] = c[index].name;
        } );

        $.ajax({
           type: "POST",
           url: url,
           data: data,
           traditional: true,
           //contentType: "application/json",
           //dataType: "text",
           success: function (data) {
              var url = data.download_url;
              window.location = url;
           },
        });
}

templates/ta_main.html
{% load staticfiles %}
{% load cache %}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>BI Monitor</title>
    <link rel="stylesheet" type="text/css" href="{% static "bootstrap/css/bootstrap.min.css" %}">
    <link rel="stylesheet" type="text/css"  href="{% static "dataTables/datatables.min.css" %}">
    <link rel="stylesheet" href="{% static "fonts/css/all.css" %}">
    <link rel="stylesheet" type="text/css"  href="{% static "jquery-ui/jquery-ui.structure.min.css" %}">
    <link rel="stylesheet" type="text/css"  href="{% static "jquery-ui/jquery-ui.theme.min.css" %}">
    <script type="text/javascript" src="{% static "jquery/jquery-1.12.4.min.js" %}"></script>
    <script type="text/javascript" src="{% static "bootstrap/js/bootstrap.bundle.min.js" %}"></script>
    <script type="text/javascript" src="{% static "dataTables/datatables.min.js" %}"></script>
    <script type="text/javascript" src="{% static "jquery-ui/jquery-ui-1.12.1.min.js" %}"></script>

    <!--
    <script type="text/javascript" src="{ % static "jquery/jquery.fileDownload.js" %}"></script>
    -->

    <!-- for chosen-select Use in dataloader
    <link rel="stylesheet" type="text/css"  href="{ % static "chosen/docsupport/prism.css" %}">
    <link rel="stylesheet" type="text/css"  href="{ % static "chosen/chosen.css" %}">
    <script type="text/javascript" src="{ % static "chosen/chosen.jquery.min.js" %}"></script>
    -->

    <!-- for select2 Use in dataloader -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

    <style type="text/css">
        table.table-hover tbody tr td:hover {
            background-color: #bfbfe0;
        }
        .navbar-nav li:hover > ul.dropdown-menu {
            display: block;
        }
        .dropdown-submenu {
            position:relative;
        }
        .dropdown-submenu>.dropdown-menu {
            top:0;
            left:100%;
            margin-top:-6px;
        }

        /* rotate caret on hover */
        .dropdown-menu > li > a:hover:after {
            text-decoration: underline;
            transform: rotate(-90deg);
        }
    </style>
</head>
<body style="padding:60px 0 0 0;">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: #0a76bf;">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarLeft" aria-controls="navbarLeft" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}"><b>BI Monitor</b></a>

      <div class="collapse navbar-collapse" id="navbarLeft">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'data:meta' %}"><i class="fa fa-database" aria-hidden="true"></i> Данные <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown active">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-chart-pie" aria-hidden="true"></i> Аналитика <span class="sr-only">(current)</span></a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'widgetpages:salesshedule' %}">График продаж</a></li>
              <li><a class="dropdown-item" href="{% url 'widgetpages:packages' %}">Анализ упаковок</a></li>
              <li><a class="dropdown-item" href="{% url 'widgetpages:avg_price' %}">Анализ средней цены</a></li>
              <li class="dropdown-submenu"><a class="dropdown-item dropdown-toggle" href="#">Конкурентный анализ</a>
                <ul class="dropdown-menu" aria-labelledby="dropdown1-1">
                    <li><a class="dropdown-item" href="{% url 'widgetpages:competitions_lpu' %}">По ЛПУ</a></li>
                    <li><a class="dropdown-item" href="{% url 'widgetpages:competitions_market' %}">По Рынкам</a></li>
                </ul>
              </li>
              <li><a class="dropdown-item" href="{% url 'widgetpages:budgets' %}">Каналы финансирования</a></li>
              <li><a class="dropdown-item"  href="{% url 'widgetpages:parts' %}">Доля</a></li>
              <li><a class="dropdown-item" href="{% url 'widgetpages:sales_analysis' %}">Анализ продаж</a></li>
              <li><a class="dropdown-item" href="{% url 'widgetpages:passport' %}">Анализ учреждений</a></li>
            </ul>
          </li>

        </ul>

        <ul class="navbar-nav mr-left">

          {% if user.is_superuser or user.is_staff or user.user_profile.is_orgadmin %}
              <li class="nav-item dropdown active">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-cogs"></i> Настройки
                </a>
                <ul class="dropdown-menu">
                  {% if user.is_superuser or user.is_staff %}{% if perms.db.view_org %}
                      <li><a class="dropdown-item" href="{% url 'farmadmin:orgselect' %}">Выбор организации</a></li>
                      <li><a class="dropdown-item" href="{% url 'farmadmin:org' org_id %}">Общие настройки</a></li>
                  {% endif %}{% endif %}

                  {% if user.is_superuser or user.is_staff or user.user_profile.is_orgadmin %}
                      {% if perms.db.view_employee %}
                        <li><a class="dropdown-item" href="{% url 'farmadmin:employees' %}">Сотрудники</a></li>
                      {% endif %}
                      {% if perms.db.view_market %}
                        <li><a class="dropdown-item" href="{% url 'farmadmin:markets' %}">Рынки</a></li>
                      {% endif %}
                  {% endif %}
                  {% if user.is_superuser or user.is_staff %}
                      <li class="dropdown-divider"></li>
                      {% if perms.db.view_org %}
                            <li><a class="dropdown-item" href="{% url 'farmadmin:orgs' %}">Организации</a></li>
                      {% endif %}
                      <li><a class="dropdown-item" href="{% url 'admin:index' %}"><i class="fa fa-wrench"></i> Администратор</a></li>
                  {% endif %}
                </ul>
              </li>
          {% endif %}

          {% if bi_auth %}
              <li class="nav-item active">
            {% if user.is_authenticated %}
                <a class="nav-link" href="{% url "logout" %}"><i class="fa fa-sign-out-alt" aria-hidden="true"></i> Выход ({{ user.username }})</a>
            {% else %}
                <a class="nav-link" href="{% url "login" %}"><i class="fa fa-sign-in-alt" aria-hidden="true"></i> Вход</a>
            {% endif %}
              </li>
          {% endif %}
         </ul>
      </div>
    </nav>

    {% if system_message %}
    <div class="alert {{ system_message.type }} alert-dismissible fade show" role="alert">
      <span>{{ system_message.text }}</span>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %}

    {% block content %}
    <main role="main">
      {% block main-content %}
      {% block body %} {% endblock %}  {# body #}
          <br>
      {% endblock %}  {# main-content #}

        <!-- Example row of columns -->
    </main>
    {% endblock %}  {# content #}

    <!-- Footer -->
    <hr class="my-3">
    <footer class="container">
     <p>&copy; BI Monitor 2018 {% if user.is_superuser or user.is_staff %} [DataSource: {{ datasource }}] {% endif %}</p>
    </footer>

    {% block js-block0 %}    {% endblock %}
    {% block js-block1 %}    {% endblock %}
    {% block js-block2 %}    {% endblock %}
</body>

</html>