TakedaAnalitic/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.views.generic import RedirectView

from bi_auth.views import loginView, logoutView, bi_login
from widgetpages.views import HomeView

urlpatterns = [
    path('', bi_login(HomeView.as_view()), name='home'),
    path('login/', loginView, name='login'),
    path('logout/', logoutView, name='logout'),
    path('page/', include(('widgetpages.urls', 'widgetpages'), namespace='widgetpages')),
    path('data/', include(('dataloader.urls', 'dataloader'), namespace='data')),
    path('fadmin/', include(('farmadmin.urls', 'farmadmin'), namespace='farmadmin')),
    # path('proto/', include(('protocols.urls', 'protocols'), namespace='protocols')),
    path('admin/', admin.site.urls, name='admin'),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico'), name='favicon'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

farmadmin/urls.py
from django.urls import path

from bi_auth.views import bi_login
from farmadmin import views


urlpatterns = [
    path('orgselect/', bi_login(views.OrgView.as_view()), name='orgselect'),
    path('setuporg/', bi_login(views.SetupOrgView.as_view()), name='setuporg'),

    path('employees/', bi_login(views.EmployeesAdminView.as_view()), name='employees'),
    #path('employee/<int:pk>/', bi_login(views.EmployeeUpdateAdminView.as_view()), name='employee'),
    path('employee/', bi_login(views.EmployeeCreateBaseAdminView.as_view()), name='employee_base'),
    path('employee/<int:pk>/', bi_login(views.EmployeeUpdateBaseAdminView.as_view()), name='employee_base'),
    path('employee/lpu/<int:pk>/', bi_login(views.EmployeeUpdateLpuAdminView.as_view()), name='employee_lpu'),
    path('employee/user/<int:pk>/', bi_login(views.EmployeeUpdateUserAdminView.as_view()), name='employee_user'),
    path('employee/reg/<int:pk>/', bi_login(views.EmployeeUpdateRegAdminView.as_view()), name='employee_reg'),
    path('employee/regquery/', bi_login(views.EmployeeQueryRegAdminView.as_view()), name='employee_regquery'),
    path('employee/rm/<int:pk>/', bi_login(views.EmployeeDeleteAdminView.as_view()), name='employee_rm'),

    path('markets/', bi_login(views.MarketsAdminView.as_view()), name='markets'),
    path('market/<int:pk>/', bi_login(views.MarketUpdateAdminView.as_view()), name='market'),
    path('market/rm/<int:pk>/', bi_login(views.MarketDeleteAdminView.as_view()), name='market_rm'),
    path('market/', bi_login(views.MarketCreateAdminView.as_view()), name='market'),

    path('orgs/', bi_login(views.OrgsAdminView.as_view()), name='orgs'),
    path('org/<int:pk>/', bi_login(views.OrgUpdateAdminView.as_view()), name='org'),
    path('org/rm/<int:pk>/', bi_login(views.OrgDeleteAdminView.as_view()), name='org_rm'),
    path('org/', bi_login(views.OrgCreateAdminView.as_view()), name='org'),

    path('jlpuall/datatable/', bi_login(views.AjaxLpuAllDatatableView.as_view()), name='jlpuall'),
    path('success/', views.SuccessView.as_view(), name='success'),
]

db/models.py
from django.db import models
from django.contrib.auth.models import User

DB_VERSION = '0.10'

DB_READY = 0
DB_UPDATE = 1
DB_RECREATE = 2
DB_OFFLINE = 3
DB_ERROR = 4

ST_NONE = 0
ST_LOAD = 1
ST_SUCCESS = 2
ST_FAILED = 3

SYNC_STATUS_CHOICES = (
    (DB_READY, 'БД в работе'),
    (DB_UPDATE, 'БД обновляется'),
    (DB_RECREATE, 'БД формируется'),
    (DB_OFFLINE, 'БД на обслуживании'),
    (DB_ERROR, 'Сбой БД'),
)

class Org(models.Model):
    name = models.CharField(max_length=32, null=True, blank=True, verbose_name='Организация')
    sync_time = models.CharField(verbose_name='Время синхронизации', max_length=5, null=True, blank=True, default='')
    sync_flag = models.BooleanField(default=False, verbose_name='Запустить формирование БД', null=False, blank=True)
    sync_status = models.IntegerField(default=0, verbose_name='Состояние синхронизации', null=False, blank=True, choices = SYNC_STATUS_CHOICES)
    users = models.ManyToManyField(User, verbose_name='Логин входа', blank=True)
    db_version = models.CharField(verbose_name='Версия БД', max_length=5, null=True, blank=True, default='0.00')
    last_sync_dt = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name = 'Организация'
        verbose_name_plural = 'Организации'

    def __str__(self):
         return  self.name

class Org_log(models.Model):
    org = models.ForeignKey(Org, on_delete=models.CASCADE)
    time = models.DateTimeField(null=False, blank=False, auto_now_add=True)
    description = models.CharField(max_length=128, null=False, blank=False, verbose_name='Сообщение')

    class Meta:
        verbose_name = 'Событие БД'
        verbose_name_plural = 'События БД'

    def __str__(self):
         return  self.description

class Lpu(models.Model):
    cust_id = models.IntegerField(db_column='Cust_ID', primary_key=True, db_index=True, null=False, blank=False)
    inn = models.CharField(db_column='Org_CustINN', max_length=16, db_index=True, null=False, blank=False, verbose_name='ИНН')
    name = models.CharField(db_column='Org_CustNm', max_length=512, db_index=True, null=False, blank=False, verbose_name='Грузополучатель')
    shortname = models.CharField(db_column='shortname', max_length=512, null=True, blank=True, verbose_name='Грузополучатель полное имя')
    addr1 = models.CharField(db_column='addr1', max_length=512, null=True, blank=True, verbose_name='Адрес1')
    addr2 = models.CharField(db_column='addr2', max_length=512, null=True, blank=True, verbose_name='Адрес2')
    regcode = models.ForeignKey('Region', db_column='regcode', null=True, verbose_name='Код региона', on_delete=models.SET_NULL)
    employee = models.ManyToManyField('Employee', related_name='employees', verbose_name='Сотрудник')

    class Meta:
        verbose_name = 'Грузополучатель'
        verbose_name_plural = 'Грузополучатели'
        managed = False
        db_table = 'db_lpu'

    def __str__(self):
         return  self.inn if self.inn else ''+' '+self.name if self.name else ''

class Region(models.Model):
    reg_id = models.IntegerField(db_column='Reg_ID', primary_key=True, db_index=True, null=False, blank=False)
    regnm = models.CharField(db_column='RegNm', max_length=50, db_index=True, null=False, blank=False, verbose_name='Название региона')
    employee = models.ManyToManyField('Employee', related_name='region_employees', verbose_name='Сотрудник')

    class Meta:
        verbose_name = 'Регион'
        verbose_name_plural = 'Регионы'
        managed = False
        db_table = 'db_region'

    def __str__(self):
         return  self.regnm

class Employee(models.Model):
    org = models.ForeignKey(Org, on_delete=models.CASCADE, verbose_name='Организация')
    parent = models.ForeignKey('self',on_delete=models.SET_NULL, null=True, blank=True, db_index=True, verbose_name='Руководитель')
    name = models.CharField(max_length=64, null=True, blank=True,verbose_name='Краткое имя')
    users = models.ManyToManyField(User, related_name='employee_user', verbose_name='Логин входа', blank=True)
    istarget = models.BooleanField(default=True, db_index=True, verbose_name='Таргет')
    lpu = models.ManyToManyField('Lpu', through=Lpu.employee.through, related_name='lpus', blank=True, verbose_name='Грузополучатели') #Lpu.employee.through
    region = models.ManyToManyField('Region', through=Region.employee.through, related_name='employee_regions', blank=True, verbose_name='Регионы')  # Region.employee.through

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'

    def __str__(self):
         return self.name

class InNR(models.Model):
    id = models.IntegerField(db_column='id', primary_key=True, db_index=True, null=False, blank=False)
    name = models.CharField(db_column='name', max_length=300, null=False, blank=False)

    class Meta:
        managed = False
        db_table = 'db_innr'

    def __str__(self):
         return  self.name

class TradeNR(models.Model):
    id = models.IntegerField(db_column='id', primary_key=True, db_index=True, null=False, blank=False)
    name = models.CharField(db_column='name', max_length=254, null=False, blank=False)

    class Meta:
        managed = False
        db_table = 'db_tradenr'

    def __str__(self):
         return  self.name

class FO(models.Model):
    id = models.IntegerField(db_column='id', primary_key=True, db_index=True, null=False, blank=False)
    name = models.CharField(db_column='name', max_length=150, null=False, blank=False)

    class Meta:
        managed = False
        db_table = 'db_fo'

    def __str__(self):
         return  self.name

class Budget(models.Model):
    id = models.CharField(db_column='id', max_length=1, primary_key=True, db_index=True, null=False, blank=False)
    version = models.IntegerField(db_column='version', db_index=True, null=False, blank=False)
    name = models.CharField(db_column='name', max_length=200, null=False, blank=False)

    class Meta:
        managed = False
        db_table = 'db_budgets'

    def __str__(self):
         return  self.name

class Unit(models.Model):
    id = models.IntegerField(db_column='id', primary_key=True, db_index=True, null=False, blank=False)
    name = models.CharField(db_column='name', max_length=40, null=False, blank=False)
    shortname = models.CharField(db_column='shortname', max_length=40, null=False, blank=False)

    class Meta:
        managed = False
        db_table = 'db_unit'

    def __str__(self):
         return  self.name

class FormT(models.Model):
    id = models.IntegerField(db_column='id', primary_key=True, db_index=True, null=False, blank=False)
    name = models.CharField(db_column='name', max_length=50, null=False, blank=False)

    class Meta:
        managed = False
        db_table = 'db_formt'

    def __str__(self):
         return  self.name

class BProg(models.Model):
    id = models.IntegerField(db_column='id', primary_key=True, db_index=True, null=False, blank=False)
    name = models.CharField(db_column='name', max_length=200, null=False, blank=False)

    class Meta:
        managed = False
        db_table = 'db_bprog'

    def __str__(self):
         return  self.name

class Market(models.Model):
    org = models.ForeignKey(Org, on_delete=models.CASCADE, verbose_name='Организация')
    name = models.CharField(max_length=32, null=True, blank=True, verbose_name='Рынок')
    innrs = models.ManyToManyField(InNR, blank=True, through='Market_Innrs', verbose_name='МНН')
    tmnrs = models.ManyToManyField(TradeNR, blank=True, through='Market_Tmnrs', verbose_name='Торговые наименования')

    class Meta:
        verbose_name = 'Рынок'
        verbose_name_plural = 'Рынки'

    def __str__(self):
         return  self.name

class Market_Innrs(models.Model):
    market = models.ForeignKey(Market, on_delete=models.CASCADE)
    innr = models.ForeignKey(InNR, on_delete=models.CASCADE)
    own = models.IntegerField(default=0, null=False, blank=False)

class Market_Tmnrs(models.Model):
    market = models.ForeignKey(Market, on_delete=models.CASCADE)
    tradenr = models.ForeignKey(TradeNR, on_delete=models.CASCADE)
    own = models.IntegerField(default=0, null=False, blank=False)

class StatusT(models.Model):
    id = models.IntegerField(db_column='id', primary_key=True, db_index=True, null=False, blank=False)
    name = models.CharField(db_column='name', max_length=40, null=False, blank=False)

    class Meta:
        managed = False
        db_table = 'db_statusT'

class WinnerOrg(models.Model):
    id = models.IntegerField(db_column='id', primary_key=True, db_index=True, null=False, blank=False)
    name = models.CharField(db_column='name', max_length=512, null=False, blank=False)
    inn = models.CharField(db_column='inn', max_length=16, null=True, blank=True)

    class Meta:
        managed = False
        db_table = 'db_WinnerOrg'

class Filters(models.Model):
    user =  models.ForeignKey(User, verbose_name='Логин входа', null=True, blank=True, db_index=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=256, null=False, blank=False, db_index=True)
    fields_json = models.TextField(null=False, blank=False)
    filters_json = models.TextField(null=False, blank=False)
    created = models.DateTimeField(null=False, blank=False, auto_now_add=True)
    updated = models.DateTimeField(null=True, blank=True, auto_now=True)
    report_start = models.DateTimeField(null=True)
    report_finish = models.DateTimeField(null=True)
    status = models.IntegerField(null=False, default=ST_NONE)
    xls_url = models.CharField(max_length=128, null=True, blank=True)
    sendmail_create = models.IntegerField(null=False, default=0)
    sendmail_shedule = models.IntegerField(null=False, default=0)

    class Meta:
        verbose_name = 'Фильтр'
        verbose_name_plural = 'Фильтры'

    def __str__(self):
         return self.name

farmadmin/templates/fa_ajax_success.html
success

farmadmin/templates/fa_employee_base.html
{% extends "fa_layout.html" %}
{% load staticfiles %}
{% load i18n %}

{% block page %}
<div class="container-fluid px-4">
<div class="row">
<div class="col-12">

<!-- Modal Confirm-->
<div class="modal" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="confirmModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="confirmModalTitle">Подтверждение запроса на удаление.</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="confirmText">
           Подтвердите удаление выбранного сотрудника.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Не удалять</button>
        <button type="button" class="btn btn-danger" id="confirmBtn">Удалить</button>
      </div>
    </div>
  </div>
</div>

<form action="{% if object %}{% url 'farmadmin:employee_base' object.id %}{% else %}{% url 'farmadmin:employee_base' %}{% endif %}" method="POST">
{% csrf_token %}
<div class="row">
      <div class="form-group col-lg-3 col-md-4 col-sm-12">
        <label for="nameInput">Сотрудник</label>
        <input type="text" class="form-control" id="nameInput" placeholder="" value="{{ object.name }}" name="name">
      </div>
</div>
<div class="row">
      <div class="form-group col-lg-3 col-md-4 col-sm-12">
        <label for="parentSelect">Руководитель</label>
        <select class="form-control" id="parentSelect" name="parent">
               <option value="" {% if p == "" %}selected{% endif %}>---</option>
           {% for p in parents %}
               <option value="{{ p.id }}" {% if p == object.parent %}selected{% endif %}>{{ p.name }}</option>
           {% endfor %}
        </select>
      </div>
</div>
<div class="row">
      <div class="form-group col-lg-3 col-md-4 col-sm-12">
        <div class="form-check">
          <input class="form-check-input" type="checkbox" value="1" name="istarget" id="isTarget" {% if object.istarget %}checked{% endif %}>
          <label class="form-check-label" for="isTarget">
            Показывать как таргет
          </label>
        </div>
      </div>
</div>
<input type="hidden" value="{{ org.id }}" name="org">
<br>
<hr>
<div class="row">
    <div class="col-12">
            <a href="{% url 'farmadmin:employees' %}" role="button" class="btn btn-secondary">Выйти без сохранения</a>
            <button type="submit" role="button" class="btn btn-primary" id="emplSubmit">Сохранить</button>
            {% if object %}<a href="#" role="button" class="btn btn-danger float-right" id="emplRemove" data-toggle="modal" data-target="#confirmModal">Удалить</a>{% endif %}
     </div>
</div>
</form>
<br>
<br>

<script>
   $("#confirmBtn").on('click', function(){
        $.ajax({
            type: 'POST',
            url: "{% if object %}{%  url 'farmadmin:employee_rm' object.id %}{% else %}{%  url 'farmadmin:employees' %}{% endif %}",
            async: false,
            data: {
                "csrfmiddlewaretoken": '{{ csrf_token }}'
            }
        })
        window.location = "{%  url 'farmadmin:employees' %}";
   });
</script>
</div>
</div>
</div>


{% endblock %}

farmadmin/templates/fa_employees.html
{% extends "fa_layout.html" %}
{% load staticfiles %}
{% load i18n %}

{% block page %}
<div class="container-fluid mx-3">
<div class="row">
    <div style="width:1200px;">
        <div class="row">
        <div class="col-6">
            <a role="button" class="btn btn-primary btn-sm" href="{% url 'farmadmin:employee_base' %}"><i class="fa fa-plus" id="addEmployee"></i> Добавить сотрудника</a>
            <a role="button" class="btn btn-primary btn-sm" href="#" id="addList"><i class="fa fa-list"></i> Добавить списком</a>
        </div>
        <div class="col-6">
             <div class="input-group input-group-sm mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">Поиск</span>
              </div>
              <input type="text" class="form-control" id="searchEmployee" placeholder="" aria-label="Search" aria-describedby="basic-addon1">
            </div>
        </div>
        </div>

        <div class="row">
        <div class="col-12">
           <table id="tblEmployee" class="table table-hover table-sm table-striped display w-100"></table>
        </div>
        </div>
    </div>
</div>
</div>

<script>
var dsEmployee = [
    {% for row in object_list %}
        [{{ row.id }}, '{{ row.name }}', '{{ row.parent.name }}', '{{ row.istarget }}','{{ row.region_count }}','{{ row.lpu_count }}', '{% for u in row.users.all %}{{ u.username }}{% if not forloop.last %}, {% endif %}{% endfor %}']{% if not forloop.last %},{% endif %}
    {% endfor %}
];


$(document).ready(function() {
    var tblEmployee = $('#tblEmployee').DataTable( {
        dom: '<"row"<"col-12"t>><"row"<"col-12"p><"col-12"i>>',
        paging : false,
        ordering:  true,
        "order": [[ 2, "asc" ]],
        data: dsEmployee,
        columns: [
            { title: "employee_id", visible: false, searchable: false},
            { title: "Сотрудник", searchable: true , //className: 'text-center',
                 render:function(data, type, row, meta) {
                     url = "{% url 'farmadmin:employee_base' 90000000000000009 %}".replace('90000000000000009',row[0]);
                     return "<a href='"+url+"'>"+data+"</a>"
                 }
            },
            { title: "Руководитель", searchable: false },
            { title: "Таргет", searchable: false, //className: 'text-center',
                 render:function(data, type, row, meta) {
                     if (data == "True") {
                         icon = "fa-check";
                         style = "color:green;"
                     }
                     else {
                         icon = "fa-times";
                         style = "color:red;"
                     }
                     return "<i style='"+ style +"' class='fa "+ icon +"'></i>"
                 }
            },
            { title: "Территории", searchable: false , //className: 'text-center',
                 render:function(data, type, row, meta) {
                     var url = "{% url 'farmadmin:employee_reg' 90000000000000009 %}".replace('90000000000000009',row[0]);
                     return "<a href='"+url+"'>Изменить <span class='badge badge-primary'>"+data+"</span></a>"
                 }
            },
            { title: "ЛПУ", searchable: false , //className: 'text-center',
                 render:function(data, type, row, meta) {
                     var url = "{% url 'farmadmin:employee_lpu' 90000000000000009 %}".replace('90000000000000009',row[0]);
                     return "<a href='"+url+"'>Изменить <span class='badge badge-primary'>"+data+"</span></a>"
                 }
            },
            { title: "Привязка аккаунтов", searchable: false , //className: 'text-center',
                 render:function(data, type, row, meta) {
                     var arr = data.split(',');
                     var badges ='';
                     arr.forEach(function(item, i, arr) {
                       badges += "<span class='badge badge-primary'>"+item+"</span> "
                     });
                     var url = "{% url 'farmadmin:employee_user' 90000000000000009 %}".replace('90000000000000009',row[0]);
                     return "<a href='"+url+"'>Изменить "+badges+"</a>"
                 }
            }
        ],
        language: lang_russian
    } );

    $("#searchEmployee").keyup(function(){
        tblEmployee.search( this.value ).draw();
    });

    //$('#tblEmployee').on('click', 'tr', function (event) {
    //    var id = tblEmployee.row(this).data()[0];
    //    location.href='{ % url 'farmadmin:employee' 90000000000000009 %}'.replace('90000000000000009',id);
    //} );

} );


</script>

{% endblock %}

farmadmin/templates/fa_layout.html
{% extends "ta_main.html" %}
{% load staticfiles %}
{% load i18n %}

{% block content %}

<script type="text/javascript">
{% include "dt_language.html" %}
{% include "dt_utils.html" %}
</script>

    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">
            {%  if user.is_admin or user.is_staff %}<a href="{% url 'farmadmin:orgselect' %}">Настройки</a>
            {% else %}Настройки
            {% endif %}
        </li>
        {% if not supressorg and org %}<li class="breadcrumb-item active" aria-current="page">{{ org.name }}</li>{% endif %}
        {% for b in breadcrumbs %}
            <li class="breadcrumb-item active" aria-current="page"><a href="{{ b.url }}">{{ b.name }}</a></li>
        {% endfor %}
        {% if object %}<li class="breadcrumb-item active" aria-current="page">{{ object.name }}</li>{% endif %}
      </ol>
    </nav>

    {% block page %}{% endblock %}

{% block afterpage %}{% endblock %}
{% endblock %}

farmadmin/templates/fa_markets.html
{% extends "fa_layout.html" %}
{% load staticfiles %}
{% load i18n %}

{% block page %}
    <style>
        tbody tr td.text-mini {
            font-size: 0.9rem;
            font-weight: 400;
            line-height: 0.9rem;
        }
    </style>

<div class="container-fluid mx-3 col-lg-8">
<div class="row">
    <div>
        <div class="row">
        <div class="col-6">
            <a role="button" class="btn btn-primary btn-sm" href="{% url 'farmadmin:market' %}"><i class="fa fa-plus" id="addMarket"></i> Добавить рынок</a>
        </div>
        <div class="col-6">
             <div class="input-group input-group-sm mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">Поиск</span>
              </div>
              <input type="text" class="form-control" id="searchMarket" placeholder="" aria-label="Search" aria-describedby="basic-addon1">
            </div>
        </div>
        </div>

        <div class="row">
        <div class="col-12">
           <table id="tblMarket" class="table table-hover table-sm table-striped display w-100">
               <thead>
               <th>market_id</th>
               <th width="10%">Рынок</th>
               <th width="50%">Международные Непатентованные наименования (МНН)</th>
               <th width="40%">Торговые наименования (TradeMark)</th>
               </thead>
               <tbody>
                 {% for row in object_list %}
                     <tr>
                     <td>{{ row.id }}</td><td>{{ row.name }}</td>
                     <td>{% for i in row.market_innrs_set.all %}{% if i.own %}<b>{{ i.innr.name }}</b>{% else %}{{ i.innr.name }}{% endif %}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
                     <td>{% for i in row.market_tmnrs_set.all %}{% if i.own %}<b>{{ i.tradenr.name }}</b>{% else %}{{ i.tradenr.name }}{% endif %}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
                     </tr>
                 {% endfor %}

               </tbody>
           </table>
        </div>
        </div>
    </div>
</div>
</div>

<script>

$(document).ready(function() {
    var tblMarket = $('#tblMarket').DataTable( {
        dom: '<"row"<"col-12"t>><"row"<"col-12"p><"col-12"i>>',
        paging : false,
        ordering:  true,
        "order": [[ 1, "asc" ]],
        columns: [
            { title: "market_id", visible: false, searchable: false},
            { title: "Рынок", searchable: true, className: 'text-bold' },
            { title: "Международные Непатентованные наименования (МНН)", searchable: false, className:'text-mini' },
            { title: "Торговые наименования (TradeMark)", searchable: false, className:'text-mini' }
        ],
        language: lang_russian
    } );

    $("#searchMarket").keyup(function(){
        tblMarket.search( this.value ).draw();
    });

    $('#tblMarket').on('click', 'tr', function (event) {
        var id = tblMarket.row(this).data()[0];
        location.href='{% url 'farmadmin:market' 90000000000000009 %}'.replace('90000000000000009',id);
    } );

} );


</script>

{% endblock %}

farmadmin/templates/fa_org_select.html
{% extends "fa_layout.html" %}
{% load staticfiles %}
{% load i18n %}

{% block page %}
<div class="container">
<div class="row">
        <br>
            <div class="jumbotron">
              <h1 class="display-4">{{ org.name }}</h1>
              <p class="lead">Указанная выше организация выбрана Вами для выполнения операций по администрированию.
                  Вы сможете выполнять различные операции по администрированию организации  <span class="badge badge-primary"> {{ org.name }} </span> в пределах имеющихся у Вас разрешений,
                  воспользовавшись пунктом меню <span class="badge badge-primary"><i class="fa fa-cogs"></i> Настройки </span></p>
              <p class="lead">Однако следует понимать, что доступ к аналитике организации определяется только привязкой Вашего Логина к сотруднику этой организации. В данный момент ваш аккаунт
                  связан с сотрудником <b>{{ user.employee_user.all.0.name }}</b> и организацией <span class="badge badge-primary"> {{ user.employee_user.all.0.org.name }} </span>
              <hr class="my-4">
              <p>Если Вам необходимо выполнять админиистрирование другой организации, выберите ее из списка ниже и нажмите "Выбор":</p>
                <form action="{% url 'farmadmin:setuporg' %}" method="GET">
                    <div class="input-group">
                      <select name="org" class="custom-select" id="orgSelect" aria-label="orgSelect_with_button">
                        <option value="0">Выберите организацию...</option>
                        {% for o in object_list %}
                            <option value="{{ o.id }}" {% if o.id == org.id %}selected{% endif %}>{{ o.name }}</option>
                        {% endfor %}
                      </select>
                      <div class="input-group-append">
                        <button class="btn btn-primary" type="submit">Выбор</button>
                      </div>
                    </div>
                </form>
            <hr class="my-4">
                <br>
                <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur ducimus facere hic id impedit inventore libero magnam minima natus nobis, sit tempora ullam, ut. Animi expedita id nemo qui unde?</p>
                <a class="btn btn-primary inline" role="button" href="{% url 'farmadmin:org' org.id %}">Настройка организации &raquo;</a>
                <a class="btn btn-primary inline" role="button" href="{% url 'farmadmin:employees' %}">Настройка сотрудников &raquo;</a>
                <a class="btn btn-primary inline" role="button" href="{% url 'farmadmin:markets' %}">Настройка рынков &raquo;</a>
            </div>

        <br>
</div>
</div>
{% endblock %}